WITH source_data AS (
  SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    CREATED_AT,
    UPDATED_AT,
    DMS_OP,
    DMS_COMMIT_TS,
    DMS_LOAD_TS,
    DMS_FILE_NAME,
    COALESCE(DMS_COMMIT_TS, UPDATED_AT, CREATED_AT) AS EFFECTIVE_TS
  FROM {{ source('raw', 'customers') }}
  WHERE DMS_OP IS NULL OR DMS_OP != 'D'
)

SELECT
  CUSTOMER_ID,
  FIRST_NAME,
  LAST_NAME,
  EMAIL,
  CREATED_AT,
  UPDATED_AT,
  DMS_COMMIT_TS,
  DMS_LOAD_TS,
  DMS_FILE_NAME
FROM source_data
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY CUSTOMER_ID
  ORDER BY EFFECTIVE_TS DESC, DMS_LOAD_TS DESC
) = 1
