WITH source AS (
    SELECT
        EMPLOYEE_ID, DEPT_ID, EMP_CODE, FULL_NAME, HIRE_DATE, SALARY,
        _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB,
        COALESCE(_DMS_COMMIT_TS, _LOADED_AT) AS _EFFECTIVE_TS
    FROM {{ source('bronze', 'erp_employees') }}
    WHERE _DMS_OPERATION IS NULL OR _DMS_OPERATION != 'D'
)
SELECT EMPLOYEE_ID, DEPT_ID, EMP_CODE, FULL_NAME, HIRE_DATE, SALARY,
       _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB
FROM source
QUALIFY ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY _EFFECTIVE_TS DESC, _LOADED_AT DESC) = 1
