WITH source AS (
    SELECT
        DEPT_ID, DEPT_CODE, DEPT_NAME, BUDGET_USD,
        _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB,
        COALESCE(_DMS_COMMIT_TS, _LOADED_AT) AS _EFFECTIVE_TS
    FROM {{ source('bronze', 'erp_departments') }}
    WHERE _DMS_OPERATION IS NULL OR _DMS_OPERATION != 'D'
)
SELECT DEPT_ID, DEPT_CODE, DEPT_NAME, BUDGET_USD,
       _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB
FROM source
QUALIFY ROW_NUMBER() OVER (PARTITION BY DEPT_ID ORDER BY _EFFECTIVE_TS DESC, _LOADED_AT DESC) = 1
