USE DATABASE MSSQL_MIGRATION_LAB;
USE SCHEMA BRONZE;

-- SQL Server had three DML triggers on SnowConvertStressDB tables.
-- Snowflake replaces them with append-only streams + scheduled tasks.
-- Each stream captures the net change set since the task last consumed it.
--
-- tr_Orders_Audit_IU         → STREAM_ORDERS_CHANGES   + TASK_ORDERS_AUDIT
-- tr_OrderItems_RecalcAndQueue → STREAM_ORDER_ITEMS_CHANGES + TASK_ORDER_ITEMS_RECALC
-- tr_Products_ListPriceAudit → STREAM_PRODUCTS_CHANGES + TASK_PRODUCTS_PRICE_AUDIT


CREATE OR REPLACE STREAM BRONZE.STREAM_ORDERS_CHANGES
    ON TABLE BRONZE.ORDERS
    APPEND_ONLY = FALSE
    COMMENT = 'Captures INSERT and UPDATE on BRONZE.ORDERS (replaces tr_Orders_Audit_IU)';

CREATE OR REPLACE TASK BRONZE.TASK_ORDERS_AUDIT
    WAREHOUSE = WH_MSSQL_MIGRATION
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_ORDERS_CHANGES')
AS
INSERT INTO BRONZE.MIGRATION_AUDIT_LOG
    (TABLE_NAME, DML_ACTION, ROW_PK, OLD_PAYLOAD, NEW_PAYLOAD, SQL_TRIGGER)
SELECT
    'Orders',
    CASE
        WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'INSERT'
        WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE  THEN 'UPDATE'
        ELSE 'DELETE'
    END,
    ORDER_ID::VARCHAR,
    NULL,
    OBJECT_CONSTRUCT(
        'ORDER_ID',     ORDER_ID,
        'CUSTOMER_ID',  CUSTOMER_ID,
        'ORDER_DATE',   ORDER_DATE,
        'STATUS',       STATUS,
        'TOTAL_AMOUNT', TOTAL_AMOUNT,
        'NOTES',        NOTES
    ),
    'TASK_ORDERS_AUDIT'
FROM BRONZE.STREAM_ORDERS_CHANGES
WHERE METADATA$ACTION = 'INSERT';


CREATE OR REPLACE STREAM BRONZE.STREAM_ORDER_ITEMS_CHANGES
    ON TABLE BRONZE.ORDER_ITEMS
    APPEND_ONLY = FALSE
    COMMENT = 'Captures DML on ORDER_ITEMS; drives header recalc and event queue';

CREATE OR REPLACE TASK BRONZE.TASK_ORDER_ITEMS_RECALC
    WAREHOUSE = WH_MSSQL_MIGRATION
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_ORDER_ITEMS_CHANGES')
AS
BEGIN
    INSERT INTO BRONZE.ORDER_EVENT_QUEUE (ORDER_ID, EVENT_TYPE, PAYLOAD)
    SELECT DISTINCT
        ORDER_ID,
        'LINE_ITEMS_CHANGED',
        OBJECT_CONSTRUCT('order_id', ORDER_ID)
    FROM BRONZE.STREAM_ORDER_ITEMS_CHANGES;

    UPDATE BRONZE.ORDERS o
    SET TOTAL_AMOUNT = (
        SELECT COALESCE(SUM(LINE_TOTAL), 0)
        FROM BRONZE.ORDER_ITEMS i
        WHERE i.ORDER_ID = o.ORDER_ID
    )
    WHERE o.ORDER_ID IN (
        SELECT DISTINCT ORDER_ID FROM BRONZE.STREAM_ORDER_ITEMS_CHANGES
    );
END;


CREATE OR REPLACE STREAM BRONZE.STREAM_PRODUCTS_CHANGES
    ON TABLE BRONZE.PRODUCTS
    APPEND_ONLY = FALSE
    COMMENT = 'Captures price changes on PRODUCTS; drives price history log';

CREATE OR REPLACE TASK BRONZE.TASK_PRODUCTS_PRICE_AUDIT
    WAREHOUSE = WH_MSSQL_MIGRATION
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_PRODUCTS_CHANGES')
AS
INSERT INTO BRONZE.PRODUCT_PRICE_HISTORY (PRODUCT_ID, OLD_PRICE, NEW_PRICE)
SELECT
    new_row.PRODUCT_ID,
    old_row.LIST_PRICE AS OLD_PRICE,
    new_row.LIST_PRICE AS NEW_PRICE
FROM BRONZE.STREAM_PRODUCTS_CHANGES new_row
JOIN BRONZE.PRODUCTS old_row
    ON old_row.PRODUCT_ID = new_row.PRODUCT_ID
WHERE new_row.METADATA$ACTION = 'INSERT'
  AND new_row.METADATA$ISUPDATE = TRUE
  AND new_row.LIST_PRICE IS DISTINCT FROM old_row.LIST_PRICE;


ALTER TASK BRONZE.TASK_ORDERS_AUDIT       RESUME;
ALTER TASK BRONZE.TASK_ORDER_ITEMS_RECALC RESUME;
ALTER TASK BRONZE.TASK_PRODUCTS_PRICE_AUDIT RESUME;
