USE DATABASE MSSQL_MIGRATION_LAB;
USE SCHEMA BRONZE;

-- SQL Server ERP triggers replaced:
--
-- tr_Employees_Audit     → STREAM_ERP_EMPLOYEES_CHANGES + TASK_ERP_EMPLOYEES_AUDIT
-- tr_PayrollLines_Recalc → STREAM_ERP_PAYROLL_LINES_CHANGES + TASK_ERP_PAYROLL_RECALC


CREATE OR REPLACE STREAM BRONZE.STREAM_ERP_EMPLOYEES_CHANGES
    ON TABLE BRONZE.ERP_EMPLOYEES
    APPEND_ONLY = FALSE
    COMMENT = 'Feeds audit log for employee inserts and updates (replaces tr_Employees_Audit)';

CREATE OR REPLACE TASK BRONZE.TASK_ERP_EMPLOYEES_AUDIT
    WAREHOUSE = WH_MSSQL_MIGRATION
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_ERP_EMPLOYEES_CHANGES')
AS
INSERT INTO BRONZE.MIGRATION_AUDIT_LOG
    (TABLE_NAME, DML_ACTION, ROW_PK, NEW_PAYLOAD, SQL_TRIGGER)
SELECT
    'ERP_EMPLOYEES',
    CASE
        WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'INSERT'
        WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE  THEN 'UPDATE'
        ELSE 'DELETE'
    END,
    EMPLOYEE_ID::VARCHAR,
    OBJECT_CONSTRUCT(
        'EMP_CODE', EMP_CODE,
        'SALARY',   SALARY,
        'DEPT_ID',  DEPT_ID
    ),
    'TASK_ERP_EMPLOYEES_AUDIT'
FROM BRONZE.STREAM_ERP_EMPLOYEES_CHANGES
WHERE METADATA$ACTION = 'INSERT';


CREATE OR REPLACE STREAM BRONZE.STREAM_ERP_PAYROLL_LINES_CHANGES
    ON TABLE BRONZE.ERP_PAYROLL_LINES
    APPEND_ONLY = FALSE
    COMMENT = 'Triggers payroll run status update on line insert/delete (replaces tr_PayrollLines_Recalc)';

CREATE OR REPLACE TASK BRONZE.TASK_ERP_PAYROLL_RECALC
    WAREHOUSE = WH_MSSQL_MIGRATION
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_ERP_PAYROLL_LINES_CHANGES')
AS
UPDATE BRONZE.ERP_PAYROLL_RUNS pr
SET STATUS = 'Adjusted'
WHERE pr.RUN_ID IN (
    SELECT DISTINCT RUN_ID
    FROM BRONZE.STREAM_ERP_PAYROLL_LINES_CHANGES
);


ALTER TASK BRONZE.TASK_ERP_EMPLOYEES_AUDIT RESUME;
ALTER TASK BRONZE.TASK_ERP_PAYROLL_RECALC  RESUME;
