USE DATABASE MSSQL_MIGRATION_LAB;
USE SCHEMA BRONZE;

-- SQL Server CRM triggers replaced:
--
-- tr_Accounts_Activity       → STREAM_CRM_ACCOUNTS_CHANGES + TASK_CRM_ACCOUNTS_ACTIVITY
-- tr_Opportunities_StageGuard → No stream equivalent; enforcement moves into
--                               SP_CRM_UPDATE_OPPORTUNITY_STAGE (04_crm_procs.sql).
--                               The task below logs stage transitions for auditing.


CREATE OR REPLACE STREAM BRONZE.STREAM_CRM_ACCOUNTS_CHANGES
    ON TABLE BRONZE.CRM_ACCOUNTS
    APPEND_ONLY = FALSE
    COMMENT = 'Feeds CRM activity log on account insert/update (replaces tr_Accounts_Activity)';

CREATE OR REPLACE TASK BRONZE.TASK_CRM_ACCOUNTS_ACTIVITY
    WAREHOUSE = WH_MSSQL_MIGRATION
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_CRM_ACCOUNTS_CHANGES')
AS
INSERT INTO BRONZE.MIGRATION_AUDIT_LOG
    (TABLE_NAME, DML_ACTION, ROW_PK, NEW_PAYLOAD, SQL_TRIGGER)
SELECT
    'CRM_ACCOUNTS',
    CASE
        WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'INSERT'
        ELSE 'UPDATE'
    END,
    ACCOUNT_CODE,
    OBJECT_CONSTRUCT('ACCOUNT_CODE', ACCOUNT_CODE, 'NAME', NAME, 'REGION', REGION),
    'TASK_CRM_ACCOUNTS_ACTIVITY'
FROM BRONZE.STREAM_CRM_ACCOUNTS_CHANGES
WHERE METADATA$ACTION = 'INSERT';


CREATE OR REPLACE STREAM BRONZE.STREAM_CRM_OPPORTUNITIES_CHANGES
    ON TABLE BRONZE.CRM_OPPORTUNITIES
    APPEND_ONLY = FALSE
    COMMENT = 'Logs opportunity stage transitions for audit trail';

CREATE OR REPLACE TASK BRONZE.TASK_CRM_OPPORTUNITIES_AUDIT
    WAREHOUSE = WH_MSSQL_MIGRATION
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_CRM_OPPORTUNITIES_CHANGES')
AS
INSERT INTO BRONZE.MIGRATION_AUDIT_LOG
    (TABLE_NAME, DML_ACTION, ROW_PK, NEW_PAYLOAD, SQL_TRIGGER)
SELECT
    'CRM_OPPORTUNITIES',
    CASE
        WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'INSERT'
        ELSE 'UPDATE'
    END,
    OPP_ID::VARCHAR,
    OBJECT_CONSTRUCT('OPP_ID', OPP_ID, 'STAGE', STAGE, 'AMOUNT_USD', AMOUNT_USD),
    'TASK_CRM_OPPORTUNITIES_AUDIT'
FROM BRONZE.STREAM_CRM_OPPORTUNITIES_CHANGES
WHERE METADATA$ACTION = 'INSERT';


ALTER TASK BRONZE.TASK_CRM_ACCOUNTS_ACTIVITY      RESUME;
ALTER TASK BRONZE.TASK_CRM_OPPORTUNITIES_AUDIT     RESUME;
