USE DATABASE MSSQL_MIGRATION_LAB;
USE SCHEMA BRONZE;

-- SQL Server Inventory triggers replaced:
--
-- tr_Sku_NoNegativeCost   → Validation moves into SP_INV_UPDATE_SKU_COST.
--                           The stream below monitors for any rows that slip
--                           through with a negative cost and flags them.
-- tr_vw_StockOrders_IOI   → INSTEAD OF INSERT on a view → SP_INV_SOFT_INSERT_STOCK_ORDER.


CREATE OR REPLACE STREAM BRONZE.STREAM_INV_SKU_CHANGES
    ON TABLE BRONZE.INV_SKU
    APPEND_ONLY = FALSE
    COMMENT = 'Monitors SKU cost changes; flags negative values that bypass the SP layer';

CREATE OR REPLACE TASK BRONZE.TASK_INV_SKU_COST_GUARD
    WAREHOUSE = WH_MSSQL_MIGRATION
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_INV_SKU_CHANGES')
AS
INSERT INTO BRONZE.MIGRATION_AUDIT_LOG
    (TABLE_NAME, DML_ACTION, ROW_PK, NEW_PAYLOAD, SQL_TRIGGER)
SELECT
    'INV_SKU',
    'CONSTRAINT_VIOLATION',
    SKU_ID::VARCHAR,
    OBJECT_CONSTRUCT('SKU_ID', SKU_ID, 'UNIT_COST', UNIT_COST, 'NOTE', 'negative cost detected'),
    'TASK_INV_SKU_COST_GUARD'
FROM BRONZE.STREAM_INV_SKU_CHANGES
WHERE METADATA$ACTION = 'INSERT'
  AND UNIT_COST < 0;


CREATE OR REPLACE STREAM BRONZE.STREAM_INV_STOCK_MOVEMENTS_CHANGES
    ON TABLE BRONZE.INV_STOCK_MOVEMENTS
    APPEND_ONLY = TRUE
    COMMENT = 'Append-only stream for new stock movement events';

CREATE OR REPLACE TASK BRONZE.TASK_INV_STOCK_AUDIT
    WAREHOUSE = WH_MSSQL_MIGRATION
    SCHEDULE  = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_INV_STOCK_MOVEMENTS_CHANGES')
AS
INSERT INTO BRONZE.MIGRATION_AUDIT_LOG
    (TABLE_NAME, DML_ACTION, ROW_PK, NEW_PAYLOAD, SQL_TRIGGER)
SELECT
    'INV_STOCK_MOVEMENTS',
    'INSERT',
    MOV_ID::VARCHAR,
    OBJECT_CONSTRUCT(
        'MOV_ID',     MOV_ID,
        'WH_ID',      WH_ID,
        'SKU_ID',     SKU_ID,
        'QTY_CHANGE', QTY_CHANGE
    ),
    'TASK_INV_STOCK_AUDIT'
FROM BRONZE.STREAM_INV_STOCK_MOVEMENTS_CHANGES;


ALTER TASK BRONZE.TASK_INV_SKU_COST_GUARD    RESUME;
ALTER TASK BRONZE.TASK_INV_STOCK_AUDIT       RESUME;
