-- ============================================================
-- BRONZE layer: LabERP_DB
-- Source: SQL Server dbo.* (LabERP_DB)
-- ============================================================

USE DATABASE MSSQL_MIGRATION_LAB;

CREATE OR REPLACE TABLE BRONZE.ERP_DEPARTMENTS (
    DEPT_ID         NUMBER          NOT NULL,   -- INT IDENTITY
    DEPT_CODE       VARCHAR(20)     NOT NULL,   -- NVARCHAR(20) UNIQUE
    DEPT_NAME       VARCHAR(120)    NOT NULL,   -- NVARCHAR(120)
    BUDGET_USD      NUMBER(18,2)    NOT NULL,   -- DECIMAL(18,2)
    _DMS_OPERATION  VARCHAR(1),
    _DMS_COMMIT_TS  TIMESTAMP_NTZ(6),
    _LOADED_AT      TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabERP_DB'
);

CREATE OR REPLACE TABLE BRONZE.ERP_EMPLOYEES (
    EMPLOYEE_ID     NUMBER          NOT NULL,   -- INT IDENTITY
    DEPT_ID         NUMBER          NOT NULL,   -- INT FK → Departments
    EMP_CODE        VARCHAR(20)     NOT NULL,   -- NVARCHAR(20) UNIQUE
    FULL_NAME       VARCHAR(200)    NOT NULL,
    HIRE_DATE       DATE            NOT NULL,
    SALARY          NUMBER(18,4)    NOT NULL,
    ROW_VER         BINARY(8),                  -- ROWVERSION → flagged, low value
    _DMS_OPERATION  VARCHAR(1),
    _DMS_COMMIT_TS  TIMESTAMP_NTZ(6),
    _LOADED_AT      TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabERP_DB'
);

CREATE OR REPLACE TABLE BRONZE.ERP_PAYROLL_RUNS (
    RUN_ID          NUMBER          NOT NULL,   -- BIGINT IDENTITY
    RUN_MONTH       CHAR(7)         NOT NULL,   -- CHAR(7) e.g. '2025-01'
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_AT      TIMESTAMP_NTZ(3),
    _DMS_OPERATION  VARCHAR(1),
    _DMS_COMMIT_TS  TIMESTAMP_NTZ(6),
    _LOADED_AT      TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabERP_DB'
);

CREATE OR REPLACE TABLE BRONZE.ERP_PAYROLL_LINES (
    LINE_ID         NUMBER          NOT NULL,   -- BIGINT IDENTITY
    RUN_ID          NUMBER          NOT NULL,   -- FK → PayrollRuns
    EMPLOYEE_ID     NUMBER          NOT NULL,   -- FK → Employees
    GROSS_PAY       NUMBER(18,4)    NOT NULL,
    NET_PAY         NUMBER(18,4),               -- AS (GrossPay * 0.92) PERSISTED — recomputed at load
    _DMS_OPERATION  VARCHAR(1),
    _DMS_COMMIT_TS  TIMESTAMP_NTZ(6),
    _LOADED_AT      TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabERP_DB'
);

CREATE OR REPLACE TABLE BRONZE.ERP_AUDIT_LOG (
    ID              NUMBER          NOT NULL,
    TABLE_NAME      VARCHAR(128)    NOT NULL,
    ACTION_TYPE     VARCHAR(10)     NOT NULL,
    PAYLOAD         VARCHAR,
    LOGGED_AT       TIMESTAMP_NTZ(3),
    _DMS_OPERATION  VARCHAR(1),
    _DMS_COMMIT_TS  TIMESTAMP_NTZ(6),
    _LOADED_AT      TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabERP_DB'
);
