-- ============================================================
-- BRONZE layer: LabCRM_DB
-- ============================================================

USE DATABASE MSSQL_MIGRATION_LAB;

CREATE OR REPLACE TABLE BRONZE.CRM_ACCOUNTS (
    ACCOUNT_ID      NUMBER          NOT NULL,   -- INT IDENTITY
    ACCOUNT_CODE    VARCHAR(30)     NOT NULL,   -- NVARCHAR(30) UNIQUE
    NAME            VARCHAR(200)    NOT NULL,
    REGION          VARCHAR(50)     NOT NULL,
    CREATED_AT      TIMESTAMP_NTZ(3),
    _DMS_OPERATION  VARCHAR(1),
    _DMS_COMMIT_TS  TIMESTAMP_NTZ(6),
    _LOADED_AT      TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabCRM_DB'
);

CREATE OR REPLACE TABLE BRONZE.CRM_CONTACTS (
    CONTACT_ID      NUMBER          NOT NULL,
    ACCOUNT_ID      NUMBER          NOT NULL,   -- FK → Accounts
    EMAIL           VARCHAR(320)    NOT NULL,
    FULL_NAME       VARCHAR(200)    NOT NULL,
    IS_PRIMARY      BOOLEAN         NOT NULL,   -- BIT DEFAULT 0
    _DMS_OPERATION  VARCHAR(1),
    _DMS_COMMIT_TS  TIMESTAMP_NTZ(6),
    _LOADED_AT      TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabCRM_DB'
);

CREATE OR REPLACE TABLE BRONZE.CRM_OPPORTUNITIES (
    OPP_ID          NUMBER          NOT NULL,
    ACCOUNT_ID      NUMBER          NOT NULL,
    TITLE           VARCHAR(200)    NOT NULL,
    STAGE           VARCHAR(40)     NOT NULL,
    AMOUNT_USD      NUMBER(18,2)    NOT NULL,
    CLOSE_DATE      DATE,
    _DMS_OPERATION  VARCHAR(1),
    _DMS_COMMIT_TS  TIMESTAMP_NTZ(6),
    _LOADED_AT      TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabCRM_DB'
);

CREATE OR REPLACE TABLE BRONZE.CRM_ACTIVITY_LOG (
    LOG_ID          NUMBER          NOT NULL,
    ENTITY          VARCHAR(50)     NOT NULL,
    ENTITY_KEY      VARCHAR(100)    NOT NULL,
    NOTE            VARCHAR(500),
    LOGGED_AT       TIMESTAMP_NTZ(3),
    _DMS_OPERATION  VARCHAR(1),
    _DMS_COMMIT_TS  TIMESTAMP_NTZ(6),
    _LOADED_AT      TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabCRM_DB'
);
