USE DATABASE MSSQL_MIGRATION_LAB;
USE SCHEMA BRONZE;


CREATE TABLE IF NOT EXISTS BRONZE.MIGRATION_AUDIT_LOG (
    AUDIT_ID       NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    TABLE_NAME     VARCHAR(128)    NOT NULL,
    DML_ACTION     VARCHAR(10)     NOT NULL,
    ROW_PK         VARCHAR(200),
    OLD_PAYLOAD    VARIANT,
    NEW_PAYLOAD    VARIANT,
    SQL_TRIGGER    VARCHAR(256),
    NEST_LEVEL     NUMBER          NOT NULL DEFAULT 0,
    CHANGED_AT     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_BY     VARCHAR(256)    NOT NULL DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS BRONZE.ORDER_EVENT_QUEUE (
    EVENT_ID       NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    ORDER_ID       NUMBER          NOT NULL,
    EVENT_TYPE     VARCHAR(40)     NOT NULL,
    PAYLOAD        VARIANT,
    CREATED_AT     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PROCESSED      BOOLEAN         NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS BRONZE.ORDERS_ARCHIVE (
    ARCHIVE_ID     NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    ORDER_ID       NUMBER          NOT NULL,
    CUSTOMER_ID    NUMBER          NOT NULL,
    ORDER_DATE     DATE            NOT NULL,
    STATUS         VARCHAR(30)     NOT NULL,
    TOTAL_AMOUNT   NUMBER(18,4)    NOT NULL,
    NOTES          VARCHAR(500),
    ARCHIVED_AT    TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    ARCHIVE_REASON VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS BRONZE.PRODUCT_PRICE_HISTORY (
    HISTORY_ID     NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID     NUMBER          NOT NULL,
    OLD_PRICE      NUMBER(18,4),
    NEW_PRICE      NUMBER(18,4)    NOT NULL,
    CHANGED_AT     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_BY     VARCHAR(256)    NOT NULL DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS BRONZE.CATEGORY_CLOSURE (
    ANCESTOR_ID    NUMBER          NOT NULL,
    DESCENDANT_ID  NUMBER          NOT NULL,
    DEPTH          NUMBER          NOT NULL,
    CONSTRAINT PK_CATEGORY_CLOSURE PRIMARY KEY (ANCESTOR_ID, DESCENDANT_ID) NOT ENFORCED
);

CREATE INDEX IF NOT EXISTS IDX_ORDER_EVENT_QUEUE_ORDER_ID ON BRONZE.ORDER_EVENT_QUEUE (ORDER_ID);
CREATE INDEX IF NOT EXISTS IDX_MIGRATION_AUDIT_TABLE_DATE  ON BRONZE.MIGRATION_AUDIT_LOG (TABLE_NAME, CHANGED_AT);
