WITH source_data AS (
  SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_DATE,
    UPDATED_AT,
    DMS_OP,
    DMS_COMMIT_TS,
    DMS_LOAD_TS,
    DMS_FILE_NAME,
    COALESCE(DMS_COMMIT_TS, UPDATED_AT, ORDER_DATE) AS EFFECTIVE_TS
  FROM {{ source('raw', 'orders') }}
  WHERE DMS_OP IS NULL OR DMS_OP != 'D'
)

SELECT
  ORDER_ID,
  CUSTOMER_ID,
  ORDER_STATUS,
  ORDER_DATE,
  UPDATED_AT,
  DMS_COMMIT_TS,
  DMS_LOAD_TS,
  DMS_FILE_NAME,
  EFFECTIVE_TS AS ORDER_UPDATED_AT
FROM source_data
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY ORDER_ID
  ORDER BY EFFECTIVE_TS DESC, DMS_LOAD_TS DESC
) = 1
