WITH source_data AS (
  SELECT
    ORDER_ITEM_ID,
    ORDER_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    CREATED_AT,
    UPDATED_AT,
    DMS_OP,
    DMS_COMMIT_TS,
    DMS_LOAD_TS,
    DMS_FILE_NAME,
    COALESCE(DMS_COMMIT_TS, UPDATED_AT, CREATED_AT) AS EFFECTIVE_TS
  FROM {{ source('raw', 'order_items') }}
  WHERE DMS_OP IS NULL OR DMS_OP != 'D'
)

SELECT
  ORDER_ITEM_ID,
  ORDER_ID,
  PRODUCT_ID,
  QUANTITY,
  UNIT_PRICE,
  CREATED_AT,
  UPDATED_AT,
  DMS_COMMIT_TS,
  DMS_LOAD_TS,
  DMS_FILE_NAME,
  EFFECTIVE_TS AS ITEM_UPDATED_AT,
  QUANTITY * UNIT_PRICE AS LINE_TOTAL
FROM source_data
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY ORDER_ITEM_ID
  ORDER BY EFFECTIVE_TS DESC, DMS_LOAD_TS DESC
) = 1
