SELECT
  CURRENT_TIMESTAMP() AS RUN_TS,
  'CUSTOMERS' AS TABLE_NAME,
  COUNT(*) AS ROW_COUNT,
  MAX(DMS_LOAD_TS) AS MAX_DMS_LOAD_TS
FROM {{ source('raw', 'customers') }}

UNION ALL

SELECT
  CURRENT_TIMESTAMP() AS RUN_TS,
  'PRODUCTS' AS TABLE_NAME,
  COUNT(*) AS ROW_COUNT,
  MAX(DMS_LOAD_TS) AS MAX_DMS_LOAD_TS
FROM {{ source('raw', 'products') }}

UNION ALL

SELECT
  CURRENT_TIMESTAMP() AS RUN_TS,
  'ORDERS' AS TABLE_NAME,
  COUNT(*) AS ROW_COUNT,
  MAX(DMS_LOAD_TS) AS MAX_DMS_LOAD_TS
FROM {{ source('raw', 'orders') }}

UNION ALL

SELECT
  CURRENT_TIMESTAMP() AS RUN_TS,
  'ORDER_ITEMS' AS TABLE_NAME,
  COUNT(*) AS ROW_COUNT,
  MAX(DMS_LOAD_TS) AS MAX_DMS_LOAD_TS
FROM {{ source('raw', 'order_items') }}
