-- ============================================================
-- SILVER layer: SnowConvertStressDB
-- Pattern: deduplicated, cleaned, computed cols resolved,
--          surrogate keys, SCD-ready, no deleted rows
-- ============================================================

USE DATABASE MSSQL_MIGRATION_LAB;
CREATE SCHEMA IF NOT EXISTS SILVER;

CREATE OR REPLACE TABLE SILVER.CATEGORIES (
    CATEGORY_SK     NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,  -- surrogate key
    CATEGORY_ID     NUMBER          NOT NULL,   -- natural key from source
    CATEGORY_NAME   VARCHAR(100)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    _VALID_FROM     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _VALID_TO       TIMESTAMP_NTZ,              -- NULL = current record
    _IS_CURRENT     BOOLEAN         NOT NULL DEFAULT TRUE,
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'SnowConvertStressDB'
);

CREATE OR REPLACE TABLE SILVER.CUSTOMERS (
    CUSTOMER_SK     NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID     NUMBER          NOT NULL,
    CUSTOMER_CODE   VARCHAR(20)     NOT NULL,
    FULL_NAME       VARCHAR(200)    NOT NULL,
    EMAIL           VARCHAR(320),
    COUNTRY         VARCHAR(100)    NOT NULL,
    CREATED_AT      TIMESTAMP_NTZ(3),
    _VALID_FROM     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _VALID_TO       TIMESTAMP_NTZ,
    _IS_CURRENT     BOOLEAN         NOT NULL DEFAULT TRUE,
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'SnowConvertStressDB'
);

CREATE OR REPLACE TABLE SILVER.PRODUCTS (
    PRODUCT_SK      NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID      NUMBER          NOT NULL,
    CATEGORY_ID     NUMBER          NOT NULL,
    SKU             VARCHAR(50)     NOT NULL,
    PRODUCT_NAME    VARCHAR(200)    NOT NULL,
    LIST_PRICE      NUMBER(18,4)    NOT NULL,
    IS_ACTIVE       BOOLEAN         NOT NULL,
    _VALID_FROM     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _VALID_TO       TIMESTAMP_NTZ,
    _IS_CURRENT     BOOLEAN         NOT NULL DEFAULT TRUE,
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'SnowConvertStressDB'
);

CREATE OR REPLACE TABLE SILVER.ORDERS (
    ORDER_SK        NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    ORDER_ID        NUMBER          NOT NULL,
    CUSTOMER_ID     NUMBER          NOT NULL,
    ORDER_DATE      DATE            NOT NULL,
    STATUS          VARCHAR(30)     NOT NULL,
    TOTAL_AMOUNT    NUMBER(18,4)    NOT NULL,
    NOTES           VARCHAR(500),
    _VALID_FROM     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _VALID_TO       TIMESTAMP_NTZ,
    _IS_CURRENT     BOOLEAN         NOT NULL DEFAULT TRUE,
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'SnowConvertStressDB'
);

CREATE OR REPLACE TABLE SILVER.ORDER_ITEMS (
    ORDER_ITEM_SK   NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    ORDER_ITEM_ID   NUMBER          NOT NULL,
    ORDER_ID        NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    QUANTITY        NUMBER          NOT NULL,
    UNIT_PRICE      NUMBER(18,4)    NOT NULL,
    LINE_TOTAL      NUMBER(18,4)    NOT NULL,   -- resolved computed col: QUANTITY * UNIT_PRICE
    _VALID_FROM     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _IS_CURRENT     BOOLEAN         NOT NULL DEFAULT TRUE,
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'SnowConvertStressDB'
);
