-- ============================================================
-- SILVER layer: LabCRM_DB
-- ============================================================

USE DATABASE MSSQL_MIGRATION_LAB;

CREATE OR REPLACE TABLE SILVER.CRM_ACCOUNTS (
    ACCOUNT_SK      NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    ACCOUNT_ID      NUMBER          NOT NULL,
    ACCOUNT_CODE    VARCHAR(30)     NOT NULL,
    NAME            VARCHAR(200)    NOT NULL,
    REGION          VARCHAR(50)     NOT NULL,
    CREATED_AT      TIMESTAMP_NTZ(3),
    _VALID_FROM     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _VALID_TO       TIMESTAMP_NTZ,
    _IS_CURRENT     BOOLEAN         NOT NULL DEFAULT TRUE,
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabCRM_DB'
);

CREATE OR REPLACE TABLE SILVER.CRM_CONTACTS (
    CONTACT_SK      NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    CONTACT_ID      NUMBER          NOT NULL,
    ACCOUNT_ID      NUMBER          NOT NULL,
    EMAIL           VARCHAR(320)    NOT NULL,
    FULL_NAME       VARCHAR(200)    NOT NULL,
    IS_PRIMARY      BOOLEAN         NOT NULL,
    _VALID_FROM     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _VALID_TO       TIMESTAMP_NTZ,
    _IS_CURRENT     BOOLEAN         NOT NULL DEFAULT TRUE,
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabCRM_DB'
);

CREATE OR REPLACE TABLE SILVER.CRM_OPPORTUNITIES (
    OPP_SK          NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    OPP_ID          NUMBER          NOT NULL,
    ACCOUNT_ID      NUMBER          NOT NULL,
    TITLE           VARCHAR(200)    NOT NULL,
    STAGE           VARCHAR(40)     NOT NULL,
    AMOUNT_USD      NUMBER(18,2)    NOT NULL,
    CLOSE_DATE      DATE,
    _VALID_FROM     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _VALID_TO       TIMESTAMP_NTZ,
    _IS_CURRENT     BOOLEAN         NOT NULL DEFAULT TRUE,
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabCRM_DB'
);
