-- ============================================================
-- SILVER layer: LabInventory_DB
-- ============================================================

USE DATABASE MSSQL_MIGRATION_LAB;

CREATE OR REPLACE TABLE SILVER.INV_WAREHOUSES (
    WH_SK           NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    WH_ID           NUMBER          NOT NULL,
    WH_CODE         VARCHAR(20)     NOT NULL,
    LOCATION        VARCHAR(200)    NOT NULL,
    _VALID_FROM     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _IS_CURRENT     BOOLEAN         NOT NULL DEFAULT TRUE,
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabInventory_DB'
);

CREATE OR REPLACE TABLE SILVER.INV_SKU (
    SKU_SK          NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    SKU_ID          NUMBER          NOT NULL,
    SKU_CODE        VARCHAR(40)     NOT NULL,
    DESCR           VARCHAR(200)    NOT NULL,
    UNIT_COST       NUMBER(18,4)    NOT NULL,
    _VALID_FROM     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _VALID_TO       TIMESTAMP_NTZ,
    _IS_CURRENT     BOOLEAN         NOT NULL DEFAULT TRUE,
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabInventory_DB'
);

CREATE OR REPLACE TABLE SILVER.INV_STOCK_MOVEMENTS (
    MOV_SK          NUMBER          NOT NULL AUTOINCREMENT PRIMARY KEY,
    MOV_ID          NUMBER          NOT NULL,
    WH_ID           NUMBER          NOT NULL,
    SKU_ID          NUMBER          NOT NULL,
    QTY_CHANGE      NUMBER          NOT NULL,
    REASON          VARCHAR(80)     NOT NULL,
    MOV_DATE        TIMESTAMP_NTZ(3),
    _VALID_FROM     TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _IS_CURRENT     BOOLEAN         NOT NULL DEFAULT TRUE,
    _SOURCE_DB      VARCHAR(128)    NOT NULL DEFAULT 'LabInventory_DB'
);

-- Running stock balance per warehouse+SKU (materialized in Silver)
CREATE OR REPLACE TABLE SILVER.INV_STOCK_BALANCE (
    WH_ID           NUMBER          NOT NULL,
    SKU_ID          NUMBER          NOT NULL,
    WH_CODE         VARCHAR(20),
    SKU_CODE        VARCHAR(40),
    CURRENT_QTY     NUMBER          NOT NULL DEFAULT 0,
    LAST_UPDATED    TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_STOCK_BALANCE PRIMARY KEY (WH_ID, SKU_ID) NOT ENFORCED
);
