WITH source AS (
    SELECT
        OPP_ID, ACCOUNT_ID, TITLE, STAGE, AMOUNT_USD, CLOSE_DATE,
        _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB,
        COALESCE(_DMS_COMMIT_TS, _LOADED_AT) AS _EFFECTIVE_TS
    FROM {{ source('bronze', 'crm_opportunities') }}
    WHERE _DMS_OPERATION IS NULL OR _DMS_OPERATION != 'D'
)
SELECT OPP_ID, ACCOUNT_ID, TITLE, STAGE, AMOUNT_USD, CLOSE_DATE,
       _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB
FROM source
QUALIFY ROW_NUMBER() OVER (PARTITION BY OPP_ID ORDER BY _EFFECTIVE_TS DESC, _LOADED_AT DESC) = 1
