WITH source AS (
    SELECT
        ACCOUNT_ID, ACCOUNT_CODE, NAME, REGION, CREATED_AT,
        _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB,
        COALESCE(_DMS_COMMIT_TS, CREATED_AT) AS _EFFECTIVE_TS
    FROM {{ source('bronze', 'crm_accounts') }}
    WHERE _DMS_OPERATION IS NULL OR _DMS_OPERATION != 'D'
)
SELECT ACCOUNT_ID, ACCOUNT_CODE, NAME, REGION, CREATED_AT,
       _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB
FROM source
QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID ORDER BY _EFFECTIVE_TS DESC, _LOADED_AT DESC) = 1
