-- =============================================================================
-- row_count_checks.sql
-- Cross-domain row count snapshot — run after every Bronze ingest.
-- Returns one row per table with its count and a PASS/WARN flag.
-- Called from: dag_04_data_quality.py → task 'bronze_row_count_report'
-- =============================================================================

SELECT
    layer,
    table_name,
    row_count,
    CASE WHEN row_count = 0 THEN 'WARN: empty' ELSE 'PASS' END AS status
FROM (

    -- Orders domain
    SELECT 'BRONZE' AS layer, 'CATEGORIES'           AS table_name, COUNT(*) AS row_count FROM MSSQL_MIGRATION_LAB.BRONZE.CATEGORIES
    UNION ALL SELECT 'BRONZE', 'CUSTOMERS',           COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.CUSTOMERS
    UNION ALL SELECT 'BRONZE', 'PRODUCTS',            COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.PRODUCTS
    UNION ALL SELECT 'BRONZE', 'ORDERS',              COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.ORDERS
    UNION ALL SELECT 'BRONZE', 'ORDER_ITEMS',         COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.ORDER_ITEMS

    -- ERP domain
    UNION ALL SELECT 'BRONZE', 'ERP_DEPARTMENTS',     COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.ERP_DEPARTMENTS
    UNION ALL SELECT 'BRONZE', 'ERP_EMPLOYEES',       COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.ERP_EMPLOYEES
    UNION ALL SELECT 'BRONZE', 'ERP_PAYROLL_RUNS',    COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.ERP_PAYROLL_RUNS
    UNION ALL SELECT 'BRONZE', 'ERP_PAYROLL_LINES',   COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.ERP_PAYROLL_LINES

    -- CRM domain
    UNION ALL SELECT 'BRONZE', 'CRM_ACCOUNTS',        COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.CRM_ACCOUNTS
    UNION ALL SELECT 'BRONZE', 'CRM_CONTACTS',        COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.CRM_CONTACTS
    UNION ALL SELECT 'BRONZE', 'CRM_OPPORTUNITIES',   COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.CRM_OPPORTUNITIES

    -- Inventory domain
    UNION ALL SELECT 'BRONZE', 'INV_WAREHOUSES',      COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.INV_WAREHOUSES
    UNION ALL SELECT 'BRONZE', 'INV_SKU',             COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.INV_SKU
    UNION ALL SELECT 'BRONZE', 'INV_STOCK_MOVEMENTS', COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.INV_STOCK_MOVEMENTS

    -- Audit / supporting
    UNION ALL SELECT 'BRONZE', 'MIGRATION_AUDIT_LOG', COUNT(*) FROM MSSQL_MIGRATION_LAB.BRONZE.MIGRATION_AUDIT_LOG

) counts
ORDER BY layer, table_name;
