WITH source AS (
    SELECT
        SKU_ID, SKU_CODE, DESCR, UNIT_COST,
        _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB,
        COALESCE(_DMS_COMMIT_TS, _LOADED_AT) AS _EFFECTIVE_TS
    FROM {{ source('bronze', 'inv_sku') }}
    WHERE _DMS_OPERATION IS NULL OR _DMS_OPERATION != 'D'
)
SELECT SKU_ID, SKU_CODE, DESCR, UNIT_COST,
       _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB
FROM source
QUALIFY ROW_NUMBER() OVER (PARTITION BY SKU_ID ORDER BY _EFFECTIVE_TS DESC, _LOADED_AT DESC) = 1
