WITH source AS (
    SELECT
        WH_ID, WH_CODE, LOCATION,
        _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB
    FROM {{ source('bronze', 'inv_warehouses') }}
    WHERE _DMS_OPERATION IS NULL OR _DMS_OPERATION != 'D'
)
SELECT WH_ID, WH_CODE, LOCATION, _DMS_OPERATION, _DMS_COMMIT_TS, _LOADED_AT, _SOURCE_DB
FROM source
QUALIFY ROW_NUMBER() OVER (PARTITION BY WH_ID ORDER BY _LOADED_AT DESC) = 1
