USE DATABASE MSSQL_MIGRATION_LAB;
USE SCHEMA BRONZE;


CREATE OR REPLACE PROCEDURE BRONZE.SP_REFRESH_ORDER_TOTALS(ORDER_ID NUMBER)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    IF (ORDER_ID IS NOT NULL) THEN
        UPDATE BRONZE.ORDERS o
        SET TOTAL_AMOUNT = (
            SELECT COALESCE(SUM(LINE_TOTAL), 0)
            FROM BRONZE.ORDER_ITEMS
            WHERE ORDER_ID = o.ORDER_ID
        )
        WHERE o.ORDER_ID = :ORDER_ID;
    ELSE
        UPDATE BRONZE.ORDERS o
        SET TOTAL_AMOUNT = (
            SELECT COALESCE(SUM(LINE_TOTAL), 0)
            FROM BRONZE.ORDER_ITEMS i
            WHERE i.ORDER_ID = o.ORDER_ID
        );
    END IF;

    RETURN 'OK';
END;
$$;


CREATE OR REPLACE PROCEDURE BRONZE.SP_LIST_OPEN_ORDERS()
RETURNS TABLE()
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET DEFAULT (
        SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS, TOTAL_AMOUNT
        FROM BRONZE.ORDERS
        WHERE STATUS = 'Open'
        ORDER BY ORDER_DATE
    );
BEGIN
    RETURN TABLE(res);
END;
$$;
