USE DATABASE MSSQL_MIGRATION_LAB;
USE SCHEMA BRONZE;


CREATE OR REPLACE PROCEDURE BRONZE.SP_ERP_DYNAMIC_DEPT_REPORT(
    P_MIN_SALARY  NUMBER,
    P_ORDER_BY    VARCHAR
)
RETURNS TABLE()
LANGUAGE SQL
AS
$$
DECLARE
    v_safe_ord  VARCHAR;
    v_where     VARCHAR DEFAULT '';
    v_sql       VARCHAR;
    res         RESULTSET;
BEGIN
    v_safe_ord := CASE
        WHEN UPPER(P_ORDER_BY) IN ('SALARY', 'HIRE_DATE', 'EMP_CODE')
            THEN UPPER(P_ORDER_BY)
        ELSE 'SALARY'
    END;

    IF (P_MIN_SALARY IS NOT NULL) THEN
        v_where := ' AND e.SALARY >= ' || P_MIN_SALARY;
    END IF;

    v_sql := '
        SELECT e.EMP_CODE, e.FULL_NAME, d.DEPT_CODE, e.SALARY
        FROM BRONZE.ERP_EMPLOYEES e
        JOIN BRONZE.ERP_DEPARTMENTS d ON d.DEPT_ID = e.DEPT_ID
        WHERE 1=1' || v_where ||
        ' ORDER BY ' || v_safe_ord;

    res := (EXECUTE IMMEDIATE :v_sql);
    RETURN TABLE(res);
END;
$$;


CREATE OR REPLACE PROCEDURE BRONZE.SP_ERP_CLOSE_PAYROLL_RUN(P_RUN_ID NUMBER)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    UPDATE BRONZE.ERP_PAYROLL_RUNS
    SET STATUS = 'Closed'
    WHERE RUN_ID = :P_RUN_ID;

    RETURN CASE WHEN SQLROWCOUNT > 0 THEN 'Closed' ELSE 'Not found' END;
END;
$$;
