USE DATABASE MSSQL_MIGRATION_LAB;
USE SCHEMA BRONZE;


CREATE OR REPLACE PROCEDURE BRONZE.SP_CRM_MERGE_ACCOUNTS_FROM_JSON(P_JSON VARIANT)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO BRONZE.CRM_ACCOUNTS tgt
    USING (
        SELECT
            value:AccountCode::VARCHAR  AS ACCOUNT_CODE,
            value:Name::VARCHAR         AS NAME,
            value:Region::VARCHAR       AS REGION
        FROM TABLE(FLATTEN(input => :P_JSON))
    ) src ON tgt.ACCOUNT_CODE = src.ACCOUNT_CODE
    WHEN MATCHED THEN
        UPDATE SET NAME = src.NAME, REGION = src.REGION
    WHEN NOT MATCHED THEN
        INSERT (ACCOUNT_CODE, NAME, REGION)
        VALUES (src.ACCOUNT_CODE, src.NAME, src.REGION);

    RETURN 'Merged ' || SQLROWCOUNT || ' accounts';
END;
$$;


CREATE OR REPLACE PROCEDURE BRONZE.SP_CRM_LIST_PIPELINE(P_REGION VARCHAR)
RETURNS TABLE()
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET DEFAULT (
        SELECT o.OPP_ID, a.ACCOUNT_CODE, o.TITLE, o.STAGE, o.AMOUNT_USD
        FROM BRONZE.CRM_OPPORTUNITIES o
        JOIN BRONZE.CRM_ACCOUNTS a ON a.ACCOUNT_ID = o.ACCOUNT_ID
        WHERE :P_REGION IS NULL OR a.REGION = :P_REGION
        ORDER BY o.AMOUNT_USD DESC
    );
BEGIN
    RETURN TABLE(res);
END;
$$;


CREATE OR REPLACE PROCEDURE BRONZE.SP_CRM_UPDATE_OPPORTUNITY_STAGE(
    P_OPP_ID    NUMBER,
    P_NEW_STAGE VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_current_stage VARCHAR;
BEGIN
    SELECT STAGE INTO v_current_stage
    FROM BRONZE.CRM_OPPORTUNITIES
    WHERE OPP_ID = :P_OPP_ID;

    IF (v_current_stage = 'Won' AND :P_NEW_STAGE != 'Won') THEN
        RETURN 'ERROR: cannot move backwards from Won';
    END IF;

    UPDATE BRONZE.CRM_OPPORTUNITIES
    SET STAGE = :P_NEW_STAGE
    WHERE OPP_ID = :P_OPP_ID;

    RETURN 'Stage updated to ' || P_NEW_STAGE;
END;
$$;
