USE DATABASE MSSQL_MIGRATION_LAB;
USE SCHEMA BRONZE;


CREATE OR REPLACE PROCEDURE BRONZE.SP_INV_DYNAMIC_WH_FILTER(P_WH_CODE VARCHAR)
RETURNS TABLE()
LANGUAGE SQL
AS
$$
DECLARE
    v_sql VARCHAR;
    res   RESULTSET;
BEGIN
    v_sql := '
        SELECT m.MOV_ID, w.WH_CODE, s.SKU_CODE, m.QTY_CHANGE
        FROM BRONZE.INV_STOCK_MOVEMENTS m
        JOIN BRONZE.INV_WAREHOUSES w ON w.WH_ID = m.WH_ID
        JOIN BRONZE.INV_SKU s ON s.SKU_ID = m.SKU_ID
        WHERE w.WH_CODE = ''' || REPLACE(:P_WH_CODE, '''', '''''') || '''';

    res := (EXECUTE IMMEDIATE :v_sql);
    RETURN TABLE(res);
END;
$$;


CREATE OR REPLACE PROCEDURE BRONZE.SP_INV_SOFT_INSERT_STOCK_ORDER(
    P_WH_ID      NUMBER,
    P_SKU_ID     NUMBER,
    P_QTY_CHANGE NUMBER,
    P_REASON     VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO BRONZE.INV_STOCK_MOVEMENTS (WH_ID, SKU_ID, QTY_CHANGE, REASON)
    VALUES (:P_WH_ID, :P_SKU_ID, :P_QTY_CHANGE, COALESCE(:P_REASON, 'via view'));

    RETURN 'Inserted movement id=' || LAST_QUERY_ID();
END;
$$;


CREATE OR REPLACE PROCEDURE BRONZE.SP_INV_UPDATE_SKU_COST(
    P_SKU_ID   NUMBER,
    P_NEW_COST NUMBER
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    IF (:P_NEW_COST < 0) THEN
        RETURN 'ERROR: SKU unit cost cannot be negative';
    END IF;

    UPDATE BRONZE.INV_SKU
    SET UNIT_COST = :P_NEW_COST
    WHERE SKU_ID = :P_SKU_ID;

    RETURN 'Updated sku_id=' || P_SKU_ID || ' cost=' || P_NEW_COST;
END;
$$;
