USE DATABASE MSSQL_MIGRATION_LAB;
USE SCHEMA BRONZE;


CREATE OR REPLACE FUNCTION BRONZE.FN_FORMAT_MONEY(AMOUNT NUMBER)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
    '$' || TO_VARCHAR(AMOUNT, '999,999,999,990.00')
$$;


CREATE OR REPLACE FUNCTION BRONZE.FN_ORDER_LINE_COUNT(P_ORDER_ID NUMBER)
RETURNS NUMBER
LANGUAGE SQL
AS
$$
    (SELECT COUNT(*) FROM BRONZE.ORDER_ITEMS WHERE ORDER_ID = P_ORDER_ID)
$$;
